py billetera_moneda/app.py "5soles" "buena"
py mause_cpu/app.py "10 kg" "2"
py alicate_tornillo/app.py "12" "extra dura "
py futbolista_balon/app.py "0.50" "23"
py escritorio_cuaderno/app.py "bueno" "2cajones"
py carro_mototaxi/app.py "13234" "BUENO"
py mochila_libro/app.py "2" "programacion"
py telvisor_control/app.py "23" "jtrekns"
py billetera_moneda/app.py "5soles" "buena"
py politico_medico/app.py "peru" "juan"
py persona_perro/app.py "df" "fdd"